services:
    mysql:
        image: mysql:5
        environment:
            MYSQL_DATABASE: microservicios
            MYSQL_USER: brandondev
            MYSQL_ROOT_PASSWORD: admin123
            MYSQL_PASSWORD: admin123
        ports:
            - '3306:3306'
        container_name: microservicios_sql
        volumes:
            - ./mysql_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: admin123
        container_name: phpmyadmin_microservicios
        ports:
            - '8080:80'
    redis:
        image: redis:6.0.7
        container_name: redis_microservicios
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - ./redis_data:/data

    redisinsight:
        image: redislabs/redisinsight:1.14.0
        container_name: redisinsight_microservicios
        restart: always
        ports:
            - '8001:8001'
        volumes:
            - ./redisinsight_data:/db
volumes:
    mysql_data:
    redis_data:
    redisinsight_data:
